### ISSUE TITLE
doesn't compile with 4.16 (  error: 'struct pp_hwmgr' has no member named 'gfx_arbiter' )

### ISSUE THREAD

**Issue by Macribit** [ktsol/dwarfing#5]
hi it doesn't compile with 4.16

```
drivers/gpu/drm/amd/amdgpu/../powerplay/smumgr/polaris10_smumgr.c: In function 'polaris10_update_sclk_threshold':
drivers/gpu/drm/amd/amdgpu/../powerplay/smumgr/polaris10_smumgr.c:2382:12: error: 'struct pp_hwmgr' has no member named 'gfx_arbiter'
   && (hwmgr->gfx_arbiter.sclk_threshold !=
            ^~
drivers/gpu/drm/amd/amdgpu/../powerplay/smumgr/polaris10_smumgr.c:2385:10: error: 'struct pp_hwmgr' has no member named 'gfx_arbiter'
     hwmgr->gfx_arbiter.sclk_threshold;
          ^~
make[6]: *** [scripts/Makefile.build:324: drivers/gpu/drm/amd/amdgpu/../powerplay/smumgr/polaris10_smumgr.o] Error 1
make[5]: *** [scripts/Makefile.build:583: drivers/gpu/drm/amd/amdgpu] Error 2
make[4]: *** [scripts/Makefile.build:583: drivers/gpu/drm] Error 2
make[3]: *** [scripts/Makefile.build:583: drivers/gpu] Error 2

```

**Comment by rumatoest** [comment]
Such things happens, and it was already described here
https://github.com/ktsol/dwarfing/issues/4#issuecomment-364116939
